SELECT DATE_FORMAT(ONLINE_SALE.SALES_DATE, '%Y') AS YEAR, 
       DATE_FORMAT(ONLINE_SALE.SALES_DATE, '%c') AS MONTH,
       COUNT(DISTINCT USER_INFO.USER_ID) AS PUCHASED_USERS,
       ROUND(COUNT(DISTINCT USER_INFO.USER_ID) / 
             (SELECT COUNT(USER_ID) 
              FROM USER_INFO 
              WHERE JOINED LIKE '2021%'), 1) 
       AS PUCHASED_RATIO

FROM USER_INFO
INNER JOIN ONLINE_SALE
ON USER_INFO.USER_ID = ONLINE_SALE.USER_ID
WHERE USER_INFO.JOINED LIKE '2021%'

GROUP BY DATE_FORMAT(ONLINE_SALE.SALES_DATE, '%Y'), 
        DATE_FORMAT(ONLINE_SALE.SALES_DATE, '%m')
ORDER BY DATE_FORMAT(ONLINE_SALE.SALES_DATE, '%Y') ASC, 
        DATE_FORMAT(ONLINE_SALE.SALES_DATE, '%m') ASC