-- 코드를 입력하세요
SELECT PRODUCT_CODE, SUM(PRICE * SALES_AMOUNT) AS SALES
FROM PRODUCT a INNER JOIN OFFLINE_SALE b
    ON a.PRODUCT_ID = b.PRODUCT_ID
GROUP BY a.PRODUCT_ID
ORDER BY SALES DESC, PRODUCT_CODE